# Generated by Django 4.0.4 on 2022-05-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('add_date', models.DateField()),
                ('original_price', models.FloatField()),
                ('benefits', models.FloatField()),
                ('info', models.TextField(null=True)),
            ],
        ),
    ]
